### ISSUE TITLE
Add a new section/page to GitHub to hold the historical Decision Log spreadsheets

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#75] opened 2017-02-02 14:58 UTC

**Comment by briandiggle** [comment] 2017-06-26 15:20
OK just to clarify, this spreadsheet contains outputs which have already be sent to providers as a result of GPConnect decision log meetings.

I'll get the document and then add a new page to the "Design Principles" area.

**Comment by briandiggle** [comment] 2017-07-04 09:20
Now have the document. In my view much of the content is already found on the specification. Some content contains supplier specific information.

My view is that it would be better to have a seperate task to update the specification where design decisions have been made but not included. Proposing to close this task and add the necessary review in a future release.

**Comment by briandiggle** [comment] 2017-11-01 09:52
Closed as duplicate of #249

**Closed by briandiggle** 2017-11-01 09:52 UTC
Labels: enhancement
