### ISSUE TITLE
Uplift the documentation around Clinical Terminologies to capture case sensitivity requirements in the FHIR standard. 

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#43] opened 2017-01-24 11:18 UTC
https://www.hl7.org/fhir/terminologies.html#required

Throughout this specification, coded values are always treated as a pair composed of "system" and "code", where the system is a URL that identifies the code system that defines the codes. Note, that system values are always case sensitive. Different code systems make their own rules as to whether the codes they define are case sensitive or not. Note that all the codes defined by FHIR itself are case sensitive and SHALL be used in the provided case (usually, but not always, lowercase).

**Comment by briandiggle** [comment] 2017-06-19 14:51
Duplicate of #94

**Closed** 2017-06-19 14:51 UTC
Labels: enhancement
