### ISSUE TITLE
Uncategorised (only?) - "The provider system returns all items that have no effective date"

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#1025] opened 2020-09-18 10:41 UTC
EMIS Comment:
" https://gpc-structured-1-5-0.netlify.app/accessrecord_structured_development_search.html#uncategorised-data

  "The provider system returns all items that have no effective date"

That clause wasn't present in 1.3.1 and only seems to be included in Uncat.

What is meant by "no effective date"?

Within EmisWeb - there will always be some sort of date allocated, even if ts record as "Not Known".

Is the above saying, for Uncat observations only, with a "NK" date, these should be returned on date filtered requests?"

Update to the spec required

**Comment by mstephens-xsl** [comment] 2020-09-18 10:47
This is a duplicate of #949

**Closed by mstephens-xsl** 2020-09-18 10:47 UTC
Labels: Structured
