### ISSUE TITLE
Filesize SLAs

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#882] opened 2019-10-21 14:43 UTC
We need an SLA around the size of the document. GP to GP project are creating an SLA for the same.

**Comment by Fitz1006** [comment] 2019-10-21 14:44
Hi Dilraj,  I had a conversation with Pete who believes that the GP2GP SLA may not work for Structured as the service operates on a batch basis and the SLA is 24 hours

**Comment by dilrajbhatia2** [comment] 2019-10-24 12:20
Hi @Fitz1006 , Thanks for letting me know. I think this issue is duplicate of #857. Matt is looking into #857

**Comment by st3v3nhunt** [comment] 2023-09-28 11:30
Closing as associated issue has been resolved/closed also.

**Closed by st3v3nhunt** 2023-09-28 11:30 UTC
Labels: Structured
